layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/img"
    values:
      image: true

repos:
  sort_by: stars # pushed
  limit: 9
  exclude:
    forks: true
    # projects:
    # - repo-name

social_media:
  twitter: vivqu
  medium: vivqu
  pinterest: vivqu
  instagram: skwishum

bio:
  header:

projects:
  - name: WorldAnimals
    web_url: https://worldanimalsapp.com
    image_url: assets/img/worldanimals_icon.png
    description: Does a dog say "woof" in Chinese?

  - name: Haiku
    web_url: https://itunes.apple.com/us/app/haiku-simple-writing-app-for-haikus/id1227312972?mt=8&ign-mpt=uo%3D4
    image_url: assets/img/haiku_icon.png
    description: Writing poems with ease

  - name: San Fransokyo
    web_url: https://www.sanfransokyopodcast.com/
    image_url: assets/img/san_fransokyo_logo.png
    image_size: 100
    description: American podcast abroad in Japan
